server:
  port: 8093
  servlet:
    context-path: /
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    #如果需要项目发布,数据库地址必须配置远程数据库
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
  
  #配置视图解析器
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
dubboookeeper://192.168.126.166:2181?backup=192.168.126.166:2182,192.168.126.166:2183
  protocol:     #指定:
  scan:
    basePackages: com.jt
  application:
    name: provider-user  #指定服务名称(必须指定)
  registry:
    address: z协议
    name: dubbo   #使用dubbo协议
    port: 20880    #服务连接时的端口号,每个服务都有自己特定的端口

#日志记录 输出数据库的日志信息.
logging:
  level: 
    com.jt.mapper: debug
